import { Hero, SearchBar, Tags } from '@/components'
import { Footer, Header } from '@/components/Layout'
import { useLocalStorage } from '@/hooks'
import { nanoid } from 'nanoid'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'

const initialPrefixTags = [
  {
    tag: 'Best',
    id: 'initial-1'
  }
]

const initialSuffixTags = [
  {
    tag: 'movies on Netflix',
    id: 'initial-2'
  }
]

const Home: NextPage = () => {
  const [prefixTags, setPrefixTags] = useLocalStorage(
    'prefixTags',
    initialPrefixTags
  )
  const [suffixTags, setSuffixTags] = useLocalStorage(
    'suffixTags',
    initialSuffixTags
  )

  useEffect(() => {
    if (prefixTags.length === 0) setPrefixTags(initialPrefixTags)
  }, [])

  useEffect(() => {
    if (suffixTags.length === 0) setSuffixTags(initialSuffixTags)
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="flex flex-col items-center w-full h-full px-4 py-8 mt-12 md:mt-[10%] lg:mt-36 md:py-0">
        <Hero />

        <SearchBar suffixTags={suffixTags} prefixTags={prefixTags} />

        <Tags
          prefixTags={prefixTags}
          setPrefixTags={setPrefixTags}
          suffixTags={suffixTags}
          setSuffixTags={setSuffixTags}
        />
      </main>

      <Footer />
    </>
  )
}

export default Home
